### ISSUE TITLE
add_node does not run plugins in vanilla_improvements, but does in 0.95.6

### ISSUE THREAD

**Issue by kamalic** [datacratic/StarCluster#23]
In vanilla_improvements, when I spin up a multi-node cluster from scratch, it runs all plugins I have configured in the the config file.  However, when I add a node with "starcluster addnode -n # clustername" or via the load balancer, it runs the default SGEplugin, but none of my configured plugins.

What is happening here?  Below is the cluster, node, volume, and one of the plugins I wrote (the ops_scratchunrestrict, which indeed does things on_add_node):

[cluster platform]
KEYNAME = starclusterbot
CLUSTER_SIZE = 1
CLUSTER_USER = sgeadmin
CLUSTER_SHELL = bash
# NODE_INSTANCE_TYPE = c3.8xlarge

NODE_INSTANCE_ARRAY = c38,r38,g28
MASTER_INSTANCE_TYPE = c3.xlarge
PLUGINS = pg_platform_paths, pg_platform_update_alternatives, pg_memreq, ops_pecreate, ops_scratchunrestrict
CONFIG_ON_MASTER=True
VOLUMES=vol1

[node c38]
INSTANCE_TYPE = c3.8xlarge
SPOT_BID = 3.00
SELECTION_FACTOR = 0.5
IMAGE_ID = ami-9d61d7f6
PUBLIC_IPS = False
PLUGINS = pg_platform_paths, pg_platform_update_alternatives, pg_memreq, ops_pec
reate, ops_scratchunrestrict

[node g28]
INSTANCE_TYPE = g2.8xlarge
SPOT_BID = 3.00
SELECTION_FACTOR = 0.8
IMAGE_ID = ami-9d61d7f6
PUBLIC_IPS = False
PLUGINS = pg_platform_paths, pg_platform_update_alternatives, pg_memreq, ops_pec
reate, ops_scratchunrestrict

[node r38]
INSTANCE_TYPE = r3.8xlarge
SPOT_BID = 3.00
SELECTION_FACTOR = 1.0
IMAGE_ID = ami-9d61d7f6
PUBLIC_IPS = False
PLUGINS = pg_platform_paths, pg_platform_update_alternatives, pg_memreq, ops_pecreate, ops_scratchunrestrict
###### 
###### 

[volume vol1]
VOLUME_ID=vol-XXXXXXX
mount_path=/home
partition=0
###### 
###### 

[plugin ops_scratchunrestrict]
setup_class = ScratchUnrestrict.ScratchUnrestrict

And here is ScratchUnrestrict.py :

from starcluster.clustersetup import ClusterSetup
from starcluster.logger import log

class ScratchUnrestrict(ClusterSetup):
     def run(self, nodes, master, user, user_shell, volumes):
          for node in nodes:
               log.info("Unrestricting scratch on %s" % (node.alias))
               node.ssh.execute('rm -rf /scratch; ln -s /mnt /scratch; chmod 1777 /mnt; mount /dev/xvdaa /tmp')
     def on_add_node(self, node, nodes, master, user, user_shell, volumes):
          log.info("Unrestricting scratch on %s" % (node.alias))
          node.ssh.execute('rm -rf /scratch; ln -s /mnt /scratch; chmod 1777 /mnt; mount /dev/xvdaa /tmp')

Output when I launch the initial cluster with "starcluster start clustername", I can see it run the various other plugins (ops_scratchunrestrict for example):

> > > Adding parallel environment 'orte' to queue 'all.q'
> > > Running plugin pg_platform_paths
> > > gns.conf 100% ||||||||||||||||||||||||||||||||||||||| Time: 00:00:00 394.49 K/s
> > > gns.sh 100% ||||||||||||||||||||||||||||||||||||||||| Time: 00:00:00 406.79 K/s
> > > threaded.pe 100% |||||||||||||||||||||||||||||||||||| Time: 00:00:00 571.58 K/s
> > > Running plugin pg_platform_update_alternatives
> > > update-alternatives [a bunch of output for all the alternatives being set up]
> > > Running plugin pg_memreq
> > > Adding SGE environment to SSH paths
> > > mem_requested.txt 100% |||||||||||||||||||||||||||||| Time: 00:00:00 744.91 K/s
> > > Configuring resources and other cluster details
> > > root@master added "mem_requested" to complex entry list
> > > changed scheduler configuration
> > > setting up mem_requested to 50G for master
> > > root@master modified "master" in exechost list
> > > Running plugin ops_pecreate
> > > Creating the threaded parallel environment
> > > Running plugin ops_scratchunrestrict
> > > Unrestricting scratch on master
> > > Configuring cluster took 0.994 mins
> > > Starting cluster took 3.134 mins

The cluster is now ready to use.

...but when I add a new node with "starcluster addnode -n 1 clustername", you can see it runs th estarcluster.plugins.sge.SGEPlugin but that's all!

> > > Launching node(s): node001
> > > SpotInstanceRequest:sir-02446xcr
> > > Waiting for one of the new nodes to be up (updating every 30s)
> > > Still waiting for spots: [SpotInstanceRequest:sir-02446xcr]
> > > 2015-09-23 08:27:10.227239+00:00 Sleeping for 30 seconds
> > > Still waiting for spots: [SpotInstanceRequest:sir-02446xcr]
> > > 2015-09-23 08:27:40.376914+00:00 Sleeping for 30 seconds
> > > Instance ids:[u'i-5f6038fc']
> > > node001 ssh is not up                                              |   0%  
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Still waiting for instances: [<Node: node001 ([NODEID])>]
> > > 2015-09-23 08:28:43.958372+00:00 Sleeping for 30 seconds
> > > node001 ssh is not up                                              |   0%  
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Still waiting for instances: [<Node: node001 ([NODEID])>]
> > > 2015-09-23 08:29:15.103292+00:00 Sleeping for 30 seconds
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Adding node: node001
> > > Running plugin starcluster.clustersetup.DefaultClusterSetup
> > > Configuring hostnames...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Configuring /etc/hosts on each node
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > /tmp/exports_qGNMsW 100% |||||||||||||||||||||||||||| Time: 00:00:00 264.27 K/s
> > > exports_GEsuDE 100% ||||||||||||||||||||||||||||||||| Time: 00:00:00 876.25 K/s
> > > Configuring NFS exports path(s):
> > > /home
> > > Mounting all NFS export path(s) on 1 worker node(s)
> > > /tmp/fstab_Si5CBz 100% |||||||||||||||||||||||||||||| Time: 00:00:00 288.61 K/s
> > > fstab_pMFbQB 100% ||||||||||||||||||||||||||||||||||| Time: 00:00:00   1.04 M/s
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Setting up NFS took 0.021 mins
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Configuring scratch space for user(s): sgeadmin
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Configuring passwordless ssh for root
> > > /tmp/known_hosts_5Bvrno 100% |||||||||||||||||||||||| Time: 00:00:00 439.64 K/s
> > > known_hosts_vpMu5S 100% ||||||||||||||||||||||||||||| Time: 00:00:00 466.03 K/s
> > > /tmp/id_rsa_6mRyZ1 100% ||||||||||||||||||||||||||||| Time: 00:00:00 218.46 K/s
> > > id_rsa_6mRyZ1 100% |||||||||||||||||||||||||||||||||| Time: 00:00:00   4.01 M/s
> > > /tmp/id_rsa.pub_8QC9iU 100% ||||||||||||||||||||||||| Time: 00:00:00 234.73 K/s
> > > id_rsa.pub_8QC9iU 100% |||||||||||||||||||||||||||||| Time: 00:00:00 697.22 K/s
> > > /tmp/authorized_keys_HvL6Hm 100% |||||||||||||||||||| Time: 00:00:00 859.34 K/s
> > > authorized_keys_HvL6Hm 100% ||||||||||||||||||||||||| Time: 00:00:00   2.41 M/s
> > > /tmp/known_hosts_f3syMl 100% |||||||||||||||||||||||| Time: 00:00:00 896.82 K/s
> > > known_hosts_f3syMl 100% ||||||||||||||||||||||||||||| Time: 00:00:00   7.35 M/s
> > > Configuring passwordless ssh for sgeadmin
> > > /tmp/known_hosts_E6WYe3 100% |||||||||||||||||||||||| Time: 00:00:00 445.57 K/s
> > > known_hosts_fOFkZs 100% ||||||||||||||||||||||||||||| Time: 00:00:00 349.53 K/s
> > > Running plugin starcluster.plugins.sge.SGEPlugin
> > > Adding node001 to SGE
> > > /tmp/exports_w61SUi 100% |||||||||||||||||||||||||||| Time: 00:00:00 301.48 K/s
> > > exports_fi3ZoF 100% ||||||||||||||||||||||||||||||||| Time: 00:00:00 845.70 K/s
> > > Configuring NFS exports path(s):
> > > /opt/sge6
> > > Mounting all NFS export path(s) on 1 worker node(s)
> > > /tmp/fstab_Xp34tN 100% |||||||||||||||||||||||||||||| Time: 00:00:00 280.41 K/s
> > > fstab_Gq5qqH 100% ||||||||||||||||||||||||||||||||||| Time: 00:00:00 961.68 K/s
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Setting up NFS took 0.021 mins
> > > Updating SGE parallel environment 'orte'
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Adding parallel environment 'orte' to queue 'all.q'
> > > Shutting down threads...
> > > 20/20 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%

**Comment by FinchPowers** [comment]
This could be an issue with the default way configuration is stored. Try starting your cluster with --config-on-master and see if it fixes the issue. It will store the configuration on the master node (/etc/starcluster) and make it very easy to edit it later on.

As I find --config-on-master so handy, I neglected testing the old configuration way so it is possible that my changes introduced a bug that I did not notice.

**Comment by kamalic** [comment]
I considered that, but config-on-master doesn't work for me due to a "timeout
!!! ERROR - Check your internet connection?"  error when trying to do the step  "File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/start.py", line 282, in execute
    save_config_on_master=self.opts.config_on_master):".  

This doesn't make any sense to me because my VPC networking works fine -- as evidenced when starting the cluster without --config-on-master.  What do you think might be going on here?  The full output is below:

$ starcluster start --config-on-master vanillaimproved  
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubunt
u/.python-eggs is writable by group/others and vulnerable to attack when used wi
th get_resource_filename. Consider a more secure location (set with .set_extract
ion_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

> > > Using default cluster template: platform
> > > Validating cluster template settings...
> > > **\* WARNING - PUBLIC IPS HAVE BEEN DISABLED!!!

This means StarCluster must be executed from a machine within the cluster's VPC
([VPCNUMBER]) otherwise it will hang forever trying to connect to the instances
.

> > > Cluster template settings are valid
> > > Starting cluster...  
> > > Launching a 1-node VPC cluster...
> > > Launching master node (ami: [AMINUMBER], type: c3.xlarge)...
> > > Creating security group @sc-vanillaimproved...
> > > Creating placement group @sc-vanillaimproved...
> > > Reservation:[RESERVATIONNUMBER]
> > > Waiting for instances to propagate...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for cluster to come up... (updating every 30s)
> > > Waiting for all nodes to be in a 'running' state...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for SSH to come up on all nodes...
> > > master ssh is not up                                               |   0%
> > > master ssh is not up                                               |   0%
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for cluster to come up took 2.152 mins
> > > The master node is
> > > Configuring cluster...
> > > Saving config on master
> > > Attaching volume [VOLUMENUMBER] to master node on /dev/sdz ...
> > > Waiting for [VOLUMENUMBER] to transition to: attached...
> > > Running plugin starcluster.clustersetup.DefaultClusterSetup
> > > Configuring hostnames...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Mounting EBS volume [VOLUMENUMBER] on /home...
> > > /tmp/fstab_Ml0XaF 100% |||||||||||||||||||||||||||||| Time: 00:00:00 255.59 K/s
> > > fstab_TyB6hw 100% ||||||||||||||||||||||||||||||||||| Time: 00:00:00 934.34 K/s
> > > Creating cluster user: sgeadmin (uid: 1001, gid: 1001)
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring scratch space for user(s): sgeadmin
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Configuring /etc/hosts on each node
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Starting NFS server on master
> > > Setting up NFS took 0.009 mins
> > > Configuring passwordless ssh for root
> > > /tmp/id_rsa_Fwr4Bs 100% ||||||||||||||||||||||||||||| Time: 00:00:00   1.04 M/s
> > > /tmp/id_rsa.pub_HbVZeK 100% ||||||||||||||||||||||||| Time: 00:00:00 235.01 K/s
> > > /tmp/authorized_keys_xo7SJu 100% |||||||||||||||||||| Time: 00:00:00 822.00 K/s
> > > /tmp/known_hosts_MwSC1f 100% |||||||||||||||||||||||| Time: 00:00:00 207.04 K/s
> > > Configuring passwordless ssh for sgeadmin
> > > /tmp/known_hosts_vIiExJ 100% |||||||||||||||||||||||| Time: 00:00:00 101.46 K/s
> > > known_hosts_CGwQBq 100% ||||||||||||||||||||||||||||| Time: 00:00:00   0.00 B/s
> > > Running plugin starcluster.plugins.sge.SGEPlugin
> > > Configuring SGE...
> > > !!! ERROR - Error occured while running plugin 'starcluster.plugins.sge.SGEPlugi
> > > n':
> > > !!! ERROR - Connection error:
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 274, in main
> > >     sc.execute(args)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/start.py", line 282, in execute
> > >     save_config_on_master=self.opts.config_on_master)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1928, in start
> > >     save_config_on_master=save_config_on_master)
> > >   File "<string>", line 2, in _start
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 112, in wrap_f
> > >     res = func(_arg, *_kargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1952, in _start
> > >     self.setup_cluster(save_config_on_master)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1961, in setup_cluster
> > >     self._setup_cluster(save_config_on_master)
> > >   File "<string>", line 2, in _setup_cluster
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 112, in wrap_f
> > >     res = func(_arg, *_kargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1975, in _setup_cluster
> > >     self.run_plugins()
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1994, in run_plugins
> > >     nodes=nodes)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 2022, in run_plugin
> > >     func(*args)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/plugins/sge.py", line 241, in run
> > >     self._setup_sge()
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/plugins/sge.py", line 141, in _setup_sge
> > >     master.ssh.execute('cp -r %s %s' % (self.SGE_FRESH, self.SGE_ROOT))
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/sshutils.py", line 579, in execute
> > >     only_printable=only_printable)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/sshutils.py", line 523, in _get_output
> > >     output = stdout.readlines() + stderr.readlines()
> > >   File "build/bdist.linux-x86_64/egg/paramiko/file.py", line 285, in readlines
> > >     line = self.readline()
> > >   File "build/bdist.linux-x86_64/egg/paramiko/file.py", line 235, in readline
> > >     new_data = self._read(n)
> > >   File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 1217, in _read
> > >     return self.channel.recv(size)
> > >   File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 598, in recv
> > >     raise socket.timeout()
> > > timeout
> > > !!! ERROR - Check your internet connection?

**Comment by FinchPowers** [comment]
And if you try to manually connect after the error it works?

**Comment by kamalic** [comment]
Yes, exactly -- the machine's network connectivity is fine, as always is the case and never is a complaint when I do it without --config-on-master, and as I can show by doing an sshmaster, it connects just fine here with the --config-on-master, so the error about "Check your internet connection?" makes no sense to me:

ubuntu@ip-172-18-4-172:~$ starcluster sshmaster vanillaimproved
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

The authenticity of host '172.18.6.23 (172.18.6.23)' can't be established.
ECDSA key fingerprint is 46:53:4a:d8:2e:82:0b:6d:51:6c:e9:3c:d3:76:1b:bf.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.18.6.23' (ECDSA) to the list of known hosts.
          _                 _           _
**/___**| |_ __ _ _ __ **_| |_   _ ___| |_ ___ _ __
\    / __| __/ _` | '**/ **| | | | / __| __/ _ \ '**|
/_  ___ \ || (_| | | | (__| | |_| __ \ ||  **/ |
  \/ |_**/____,_|_|  _**|_|\**,_|___/_____|_|

StarCluster Ubuntu 12.04 AMI
Software Tools for Academics and Researchers (STAR)
Homepage: http://star.mit.edu/cluster
Documentation: http://star.mit.edu/cluster/docs/latest
Code: https://github.com/jtriley/StarCluster
Mailing list: starcluster@mit.edu

This AMI Contains:
- NVIDIA Driver 313.26
- NVIDIA CUDA Toolkit 5.0, V0.2.1221
- PyCuda/PyOpenCL 2012.1
- MAGMA 1.3.0
- Open Grid Scheduler (OGS - formerly SGE) queuing system
- Condor workload management system
- OpenMPI compiled with Open Grid Scheduler support
- OpenBLAS - Highly optimized Basic Linear Algebra Routines
- NumPy/SciPy linked against OpenBLAS
- Julia linked against OpenBLAS
- IPython 0.13 with parallel support
- and more! (use 'dpkg -l' to show all installed packages)

Open Grid Scheduler/Condor cheat sheet:
- qstat/condor_q - show status of batch jobs
- qhost/condor_status- show status of hosts, queues, and jobs
- qsub/condor_submit - submit batch jobs (e.g. qsub -cwd ./job.sh)
- qdel/condor_rm - delete batch jobs (e.g. qdel 7)
- qconf - configure Open Grid Scheduler system

Current System Stats:

  System load:    0.67             Processes:           106
  Usage of /home: 1.5% of 9.84GB   Users logged in:     0
  Memory usage:   2%               IP address for eth0: 172.18.6.23
  Swap usage:     0%

```
https://landscape.canonical.com/
```

  System information as of Thu Sep 24 21:55:25 UTC 2015

  System load:    0.67             Processes:           105
  Usage of /home: 1.5% of 9.84GB   Users logged in:     0
  Memory usage:   2%               IP address for eth0: 172.18.6.23
  Swap usage:     0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

root@master:~#

**Comment by FinchPowers** [comment]
I must say that I don't really know what is going on then. I'm sorry that it doesn't work for you. Since this version is a side product of our current environment, I'm pleased to have it available openly, but I do not have the necessary bandwidth to do more than minimal support.

If you do find the fix though, I will be happy to integrate it back.

Thanks for taking the time to try. :)

**Comment by kamalic** [comment]
Thanks -- I'll take a shot at fixing it myself and hopefully we can integrate it back into the version.  I'll keep you updated on my progress.

**Comment by kamalic** [comment]
I'm realizing that in reading over our email correspondence back in December with the person who originally told us about the vanilla improvements fork, I see that he indeed mentioned that he had made some patches to fix problems he found in the fork and that he had already been working with you to get them incorporated, and this includes a fix for the problem where plugins are not executed if the cluster is not created with --config-on-master:
- Plugins are not executed when new nodes are started if the cluster 
  was not created with --config-on-master. (I think this is because 
  plugin_order is only stored when config-on-master is used) 
- issue where load balancer will abort if there are workers of different types running. 
- I got the error "the encrypted flag cannot be specified" when creating a cluster which was avoidable changing the boto version in setup.py. (Although it could be fixed in other ways) 
- the "starcluster terminate -f" command is broken when the master node is offline.

So it sounds like you probably already have the patches for these already from him.  Can you share them?  I'm going to ask him directly, too.

Thanks!
Dan

**Comment by FinchPowers** [comment]
I don't seem to have any pending pull request for that.
https://github.com/datacratic/StarCluster/pulls

Do you have a user name or something I could use to search in my mail?

**Comment by kamalic** [comment]
Github username is pgm.  The only pull I see from him is https://github.com/datacratic/StarCluster/pull/11 , but I have sent an email directly to your email address with what he mentioned regarding the other issues.

**Comment by pgm** [comment]
Ah!   Now that I re-read this more thoroughly, I have to admit, I have this problem all the time!

There's a lot of text here, but I'll summarize my understanding as: 
A timeout in reading from the socket while waiting for "Configuring SGE..." to complete.

Yes, so at some point I too saw this, and resolved it in-house by increasing the timeout that starcluster uses for connections.   If I understand the code correctly, as-written, it assumes that you'll receive some data quickly.   Which in the case of configuring SGE isn't always the case.  (I think it sometimes takes a minute or too)

Specifically: this commit in my repo https://github.com/pgm/StarCluster/commit/f3dacd7a93245d4281c2b3be1721a076adbc7210

I just assumed it was an issue specific to me and I wasn't sure what the downside of increasing the timeout was so I never pushed it back.

**Comment by FinchPowers** [comment]
That's a big timeout. Are you using tiny instances? I wonder what makes it take so much time.

**Comment by pgm** [comment]
I too have wondered.  :)  And I think it doesn't _always_ take so long.
However, it was happening enough that I just changed it.   It's only large
because I picked an arbitrarily large number.

My arbitrary large number is another reason why I avoided pushing this as a
patch.

If I was to do this cleanly, I think I'd change it so a timeout could be
set for a single ssh command, because it's really only one command that
takes over 30 seconds.

**Comment by kamalic** [comment]
That solved it.  Fantastic!  It's possible 300 seconds would be more than enough for the timeout rather than 3000, but we can play with that.  FYI, I am using c3.xlarge for the masters, so definitely not tiny.

**Comment by FinchPowers** [comment]
@kamalic can you see if PR #28 fixes your plugin issue?

**Comment by FinchPowers** [comment]
Should be fixed by PR #28. Reopen if it did not fix the issue.
