### ISSUE TITLE
Can't remove nodes when using SGE plugin

### ISSUE THREAD

**Issue by goraxan** [datacratic/StarCluster#30]
In vanilla_improvements, every time I try to remove a node when using SGE plugin it fails leaving the cluster inconsistent. The result is that the node still appears in the all.q queue after being removed (in 'au' state), as the "qstat -f" command reveals when executed in the master:

root@master:~# qstat -f
queuename                      qtype resv/used/tot. load_avg arch          states
all.q@node001                  BIP   0/0/1          -NA-     linux-x64     au

I need to use the SGE plugin because I need the master not being able to execute anything and have 1 slot per host.

The interesting parts of my configuration are (note I'm using the official starcluster AMI in eu-west for this test):

NODE_IMAGE_ID = ami-044abf73
CLUSTER_SIZE = 2
PLUGINS = sge
DISABLE_QUEUE=True

[plugin sge]
SETUP_CLASS = starcluster.plugins.sge.SGEPlugin
MASTER_IS_EXEC_HOST = False
slots_per_host = 1

Any thoughts?
Thanks!

**Comment by goraxan** [comment]
As a comment, as said in https://github.com/datacratic/StarCluster/issues/23, when I initialize the cluster with the --config-on-master flag it works just fine. So it looks like plugins are not being executed correctly without that flag.

Any idea why this might be happening?

**Comment by FinchPowers** [comment]
Might be related to PR #28. Can you tell me whether it is now fixed or not?
Thanks
