### ISSUE TITLE
Choosing Best Spot Price Across Multiple Subnets?

### ISSUE THREAD

**Issue by xanderdunn** [datacratic/StarCluster#41]
The README mentions support for multiple subnets to get the spot price in the cheapest zone.

In my Starcluster config, I have three subnets defined:

```
SUBNET_IDS=subnet-c91f9a90, subnet-7f064b1a, subnet-7825460f
```

They are us-west-2c, us-west-2a, and us-west-2b, respectively.  However, with ~200 runs, they were all chosen to be in 2c, the first one listed.  The price in 2c went up to 0.1, while the other two zones remained around 0.02.  See the time around 8:00:

![screen_shot_2016-01-19_at_10 46 23_720](https://cloud.githubusercontent.com/assets/1313618/12429512/81b1bee6-be9f-11e5-97e5-566d065a6220.png)

**Comment by FinchPowers** [comment]
Check your `~/.starcluster/logs/debug.log`, you should find debug output generated from https://github.com/datacratic/StarCluster/blob/1e24a8290c5f18969bcceaee46953d84040be93d/starcluster/cluster.py#L1104 one or few lines before `Selected instance type`

Your zones may not be configured properly. Check with the printconfig command to confirm StarCluster reads your settings properly. Also, if you did not start your cluster with the --config-on-master case, that may be the issue.

**Comment by xanderdunn** [comment]
I haven't been using `--config-on-master`, so I'll add that.  

However, the cluster config is showing the subnets correctly:

```
$ starcluster -c /sw/sbin/starcluster_config printconfig c4cluster
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

Core settings
{
 "availability_zone": null,
 "cluster_size": 1,
 "disable_cloudinit": false,
 "disable_queue": true,
 "dns_prefix": false,
 "dns_suffix": false,
 "master_image_id": null,
 "master_instance_type": "c4.large",
 "node_instance_array": [
  {
   "image_id": "ami-c5f3e9a4",
   "instance_type": "c4.large",
   "selection_factor": 1,
   "size": 0,
   "spot_bid": null
  }
 ],
 "plugins_order": [
  "SGEPlugin"
 ],
 "public_ips": true,
 "subnet_ids": [
  "subnet-c91f9a90",
  "subnet-7f064b1a",
  "subnet-7825460f"
 ]
}

User settings
{
 "cluster_shell": "bash",
 "cluster_user": "sgeadmin",
 "keyname": "starcluster_key"
}
starcluster.plugins.sge.SGEPlugin - () - {'slots_per_host': '1', 'master_is_exec_host': 'False'}
```

Note that I checked the config on a non-spot cluster, but all other settings are the same as the spot cluster.  I'll do the same check on a spot cluster when I test if `--config-on-master` solves this.

Do you expect the log output to end up on `~/.starcluster/logs/debug.log` of the user who's executing the loadbalancer?

**Comment by FinchPowers** [comment]
> Do you expect the log output to end up on ~/.starcluster/logs/debug.log of the user who's executing the loadbalancer?

Yes.

With what you pasted here it should work already, regardless of the --config-on-master option.

**Comment by xanderdunn** [comment]
Thanks.  The loadbalancer runs as a root user background service:

```
root      8094  0.1  0.4 1438900 38276 ?       Sl   13:04   0:09 /usr/bin/python /usr/local/bin/starcluster -c /sw/sbin/starcluster_config loadbalance -m 300 -n 1 -a 20 -w 970 c4cluster
```

The logs in /root/.starcluster/logs/ are very long, but the term "selected" never occurs in any of them: [logs.zip](https://github.com/datacratic/StarCluster/files/96689/logs.zip).

**Comment by FinchPowers** [comment]
Your log "0" and 1 seem to add non spot instances.
Your log 2 adds a spot instance but has indeed no trace of the zone selection.
Try to add a node manually (starcluster .... addnode) and quickly cancel if it you don't want it. Then check the logs. If there is still no trace of the zone selection, you may have a version issue or something. Check your code and rerun the installer.

What you should see is something like

```
2016-01-18 14:40:57,205 *** WARNING - Adding 10 nodes at 2016-01-18 19:40:57.205836+00:00
2016-01-18 14:40:58,075 >>> Launching node(s): node058, node059, ...
2016-01-18 14:41:01,983 *** WARNING - no spot price history for the dates specified: None - None
2016-01-18 14:41:04,075 >>> Selected instance type r3.8xlarge with minimal price of 0.339300 in zone us-east-1d
...
```

If you still don't see it I suggest you add some debug output and try to track it down as I can't really help more than guiding you around.

**Comment by xanderdunn** [comment]
I think the debug logs cycled out the interesting part much faster than I expected.

Thanks a lot for the guidance.  I'll take a proper look and add logging if necessary.

**Comment by FinchPowers** [comment]
@xanderdunn any news on that one?
