### ISSUE TITLE
Longer EC2 and EBS Resource IDs

### ISSUE THREAD

**Issue by erikedlund** [datacratic/StarCluster#42]
https://aws.amazon.com/ec2/faqs/#longer-ids

Amazon is increasing the length of EC2 and EBS resource identifiers. "The new identifier format will follow the pattern of the current identifier format, but it will be longer. The new format will be <resource identifier>-<17 characters>, e.g. “i-1234567890abcdef0” for EC2 instances or “vol-1234567890abcdef0” for EBS volumes."

This has the potential to impact software that makes assumptions about the length of these identifiers. Do any such assumptions exist in StarCluster? Will any changes need to be made to StarCluster or boto to handle this?

**Comment by FinchPowers** [comment]
In terms of boto, good point. I don't know.
In terms of StarCluster, I don't think so, but I'm not sure.

**Comment by FinchPowers** [comment]
Logs submitted here https://github.com/datacratic/StarCluster/issues/41 have the long ids, suggesting it works as is. :)
