### ISSUE TITLE
Disable NFS?

### ISSUE THREAD

**Issue by xanderdunn** [datacratic/StarCluster#43]
I don't believe there is currently a switch to disable Starcluster's default NFS mounting of /home, is there?  

If not, could you point me in the direction in the code where I might disable it/add a switch for it?  I have no use for the NFS mount and it takes quite a long time on every node that Starcluster starts.

Thanks!

**Comment by FinchPowers** [comment]
There is no options. Here is the related code that I found.
https://github.com/datacratic/StarCluster/blob/1e24a8290c5f18969bcceaee46953d84040be93d/starcluster/clustersetup.py#L451

https://github.com/datacratic/StarCluster/blob/1e24a8290c5f18969bcceaee46953d84040be93d/starcluster/clustersetup.py#L360

https://github.com/datacratic/StarCluster/blob/1e24a8290c5f18969bcceaee46953d84040be93d/starcluster/clustersetup.py#L400
