### ISSUE TITLE
how about a 'starcluster makeami' command

### ISSUE THREAD

**Issue by cariaso** [datacratic/StarCluster#56]
http://star.mit.edu/cluster/mlarchives/2753.html
and
the thread before it suggests that the discussion has happened and it may be time for formal code instead of human hands.

My immediate need is ubuntu14 or 16 amis in non-us-east-1 regions, and I'm sure I'm not the only one. The current situation with broken ubuntu13 amis still present in listpublic is definitely suboptimal.

So I'm thinking about introducing a new command into starcluster which will allow it to make it's own amis. This might also allow you to 'bake' an ami after all of your plugin installs have completed, to reduce setup time for new worker nodes.

it would largely follow the steps from
http://star.mit.edu/cluster/mlarchives/2545.html
and would probably have a command line interface similar to

starcluster makeami --baseami ami-ed82e39e

obviously a new command is a more dramatic change than a new plugin. So before I jump in I thought I'd see if others would weigh in.

Is it useful? or perhaps impractical for reasons I'm overlooking?

**Comment by FinchPowers** [comment]
This is how I do it.
1. I take a working AMI and boot it.
2. I apply the update/changes I want.
3. I go to the AWS console and hit the "create image" button.

If you think a command would make that easier then why not, give it a shot.

Just in case: http://star.mit.edu/cluster/docs/latest/manual/create_new_ami.html
